name: Style dictionary build

on:
  push:
    paths:
      - 'data/tokens.json'
      - 'config.json'
      - 'build.js'
    branches-ignore:
      - 'main'

jobs:
  transform_tokens:
    name: "Token transformer"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Node Dependencies
        run: npm install
      - name: Run token transformer
        run: npm run transform
      - name: Commit transformed tokens
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Transformed tokens

  build_style_dictionary:
    needs: transform_tokens
    name: "Style Dictionary build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Node Dependencies
        run: npm install
      - name: Pull transformed tokens changes
        run: git pull origin ${{ github.head_ref }}
      - name: Run style dictionary build
        run: npm run build
      - name: Commit built tokens
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built and updated design tokens
